projName:=BlinkLED_MSP430FR2433_03

msp430DebugNameS:=Debug__GNU Debug__TI Debug Debug__TIT Debug__TIH
projFullName:=test for BlinkLED_MSP430FR2433_03

testOBJs:=tt5 tt1 tt2 tt3 tt4
testOBJs:=tt1


##### Project custom define : begin
b1:
	gcc
t: ttt
##### Project custom define : end




define helpText2
endef
export helpText2

